### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by BenWe** [sendyhalim/Swime#1]
Could you add support for Cocoapods? Would be convenient ;) thanks!

**Comment by sendyhalim** [comment]
Sure, I'll take a look at it this weekend 🍻 !

**Comment by sendyhalim** [comment]
Hey I just merged a PR to add support to Cocoapods https://github.com/sendyhalim/Swime/pull/2 🎉 

Let me know if I'm missing something

**Comment by sendyhalim** [comment]
Closing this since it's merged, feel free to reopen.
