### ISSUE TITLE
Trunk Please

### ISSUE THREAD

**Issue by Hackice** [sendyhalim/Swime#12]
As far as I know, the latest version of Swime on CocoaPods is 3.0.1, and the Swime.podspec file has not been updated to the correct state in this repo. Do you give up support for CocoaPods?😢

**Comment by sendyhalim** [comment]
Hi, I just bump the podspec to `3.0.6` and `pod trunk push Swime.podspec`, it's just I forgot to update the podspec, been away from swift for a while :( 

Thank you for the issue though 🍻 !
