### ISSUE TITLE
Crash when using a fake png with 15 bytes

### ISSUE THREAD

**Issue by alobaili** [sendyhalim/Swime#20]
Hello everyone,

I stubbled upon this package after a long Google search and landing on: https://sendyhalim.github.io/blog/posts/swift/detect-mime-type-with-swime/

Thank you very much for this package.

I decided to use it on my Vapor app to get the mime type of file uploads (not trusting the user provided mime type and extension).

I created a file called `fake.png` with the following 15 bytes:
```
evil text here
```

On my application I have the following code in my request handler:
```swift
guard
    let data = request.body.data, // This is a SwiftNIO.ByteBuffer
    let bytes = data.getBytes(at: 0, length: data.readableBytes) // This is a [UInt8] with count 15
else {
    throw Abort(.badRequest)
}

guard
    let mimeType = Swime.mimeType(bytes: bytes), // crash here
    mimeType.mime.lowercased().contains("image")
else {
    throw Abort(.unsupportedMediaType)
}
```

Specifically, the crash happens on line 577 in `MimeType.swift`

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27203112/140617134-6ce94515-c4fc-4cdc-9286-318b720c3dc0.png">

Is this a bug in the package or am I somehow using it incorrectly?
I think there might be a better way to handle this case.

**Comment by alobaili** [comment]
Digging deeper into this and I noticed another possible mistake. The wrong MIME type may have been assigned to the EOT extension.
According to [`file(1)`'s magic pattern for EOT](https://github.com/file/file/blob/f01a4214ac4c1b5cb9cc67916c430f743b1581d3/magic/Magdir/fonts#L364-L371), the MIME type should be `application/vnd.ms-fontobject`.

From my understanding of the linked magic pattern, All of the following patterns should be matched:
* Starting from byte 0x40, 16 bytes should be 0
* Byte 0x22 should be the letter L (0x4c)
* Byte 0x23 should be the letter P (0x50)
* Byte 0x52 should not be 0

Therefor, the value of `bytesCount` should be 82, and the `matches` property should be changed.

I tested this pattern in only one EOT file
[open-sans-v27-latin-regular.eot.zip](https://github.com/sendyhalim/Swime/files/7500063/open-sans-v27-latin-regular.eot.zip) and it seems to be the correct pattern.

**Comment by sendyhalim** [comment]
> Digging deeper into this and I noticed another possible mistake. The wrong MIME type may have been assigned to the EOT extension. According to [`file(1)`'s magic pattern for EOT](https://github.com/file/file/blob/f01a4214ac4c1b5cb9cc67916c430f743b1581d3/magic/Magdir/fonts#L364-L371), the MIME type should be `application/vnd.ms-fontobject`.
> 
> From my understanding of the linked magic pattern, All of the following patterns should be matched:
> 
> * Starting from byte 0x40, 16 bytes should be 0
> * Byte 0x22 should be the letter L (0x4c)
> * Byte 0x23 should be the letter P (0x50)
> * Byte 0x52 should not be 0
> 
> Therefor, the value of `bytesCount` should be 82, and the `matches` property should be changed.
> 
> I tested this pattern in only one EOT file [open-sans-v27-latin-regular.eot.zip](https://github.com/sendyhalim/Swime/files/7500063/open-sans-v27-latin-regular.eot.zip) and it seems to be the correct pattern.
> 
> BTW, this is the first time ever that I know of the existence of `man`, `file`, `magic` and `hexdump` 😆

Wow thanks for the explanation, that's a pretty deep digging 🚀  , so basically what I understand the bug is fixed by fixing the EOT matching properties to remove possible intersection of magic bytes pattern between `eot` and `png` 🤔 , TIL.
