### ISSUE TITLE
HEIC file type ? 

### ISSUE THREAD

**Issue by mvn-daiho-dn** [sendyhalim/Swime#4]
I would like to know why there is no .heic file type?

About HEIC file: 
https://fileinfo.com/extension/heic
https://www.theverge.com/2017/9/19/16332192/apple-ios-11-heic-iphone-image-format

**Comment by sendyhalim** [comment]
@at-daiho Hi sorry for late response, been busy lately. If I remember correctly, I just implemented the bytes signature that's listed on https://en.wikipedia.org/wiki/List_of_file_signatures and I wrote the code before iOS11 was out, I'm open for a pull request though ;)

**Comment by sendyhalim** [comment]
@at-daiho Good news! I just checked https://github.com/sindresorhus/file-type/blob/master/index.js#L736-L764 and you'll see an implementation to check HEIC file, I'll give it a shot tonight.

**Comment by NicolasKim** [comment]
I want to use this package in serverside-swift framework(Vapor). Can you implement this package without Foundation module?

**Comment by MuhtasimTanmoy** [comment]
@sendyhalim  `HEIC` check implementation moved to [this link](https://github.com/sindresorhus/file-type/blob/4ce68386d3c16dce80bc6cd407c94e82db483182/core.js#L481). Added support and tested at pull request #23 .
