### ISSUE TITLE
Crash when filesize < 262 bytes

### ISSUE THREAD

**Issue by rweichler** [sendyhalim/Swime#5]
[This line](https://github.com/sendyhalim/Swime/blob/9c0b5a49917357abe4883b3f37a5e0c28b1bf65c/Sources/Swime.swift#L52) hits an EXC_BREAKPOINT because it tries to copy to a `Data` object that has less than 262 bytes.

**Comment by muhrifqii** [comment]
hello, is there any solution for this?

**Comment by sendyhalim** [comment]
@muhrifqii Sorry for a very long delay on the fixes. I just made a pull request, waiting for tests to pass then I'll publish a new version

**Comment by sendyhalim** [comment]
I'm closing this, it's merged and published, feel free to reopen.
